# Generated by Django 6.1.1 on 2026-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique Student ID (e.g., STU001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text="Student's full name", max_length=120)),
                ('register_number', models.CharField(help_text='Official Register / Roll Number', max_length=50, unique=True)),
                ('department', models.CharField(help_text='Academic Department (e.g., Computer Science)', max_length=100)),
                ('email', models.EmailField(help_text='Valid email address', max_length=150)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
