services:
  - type: web
    name: student-management-backend
    runtime: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend.vercel.app"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
